version: '3'
services:
  puppetdb:
    build: .
    image: puppetdb:latest
    hostname: puppetdb.example.com
    restart: unless-stopped
    networks:
      puppetnet:
        aliases:
          - puppetdb.example.com
      postgres_db:
    environment:
      PUPPETDB_DATABASE_SERVER: "db"
      CERTNAME: "puppetdb.example.com"
      PUPPETDB_DATABASE_USER: "puppetdb"
      PUPPETDB_DATABASE_PASSWORD: "puppetdb"
      PUPPETDB_JAVA_ARGS: "-Xmx192m"
      DEBUG: "true"
    ports:
      - "8081:8081"
      - "9999:8080"
    volumes:
      - puppetdb-ssl:/etc/puppetlabs/puppet/ssl

  # postgres:
  #   image: puppet/puppetdb-postgres
  #   hostname: postgres.example.com
  #   restart: unless-stopped
  #   networks:
  #     puppetnet:
  #       aliases:
  #         - postgres.example.com
  #     postgres_db:
  #   environment:
  #     POSTGRES_PASSWORD: "puppetdb"
  #     POSTGRES_USER: "puppetdb"
  #   ports:
  #     - "5432:5432"

networks:
  puppetnet:
    external: true
  postgres_db:
    external: true

volumes:
  puppetdb-ssl:
